version: '3.8'

services:
  crud-test-api:
    image: crud-test-api:latest
    build:
      context: .
      dockerfile: Mc2.CrudTest.Presentation/Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sql-server;Database=Crud-test-DB;User Id=sa;Password=Ali1234567;MultipleActiveResultSets=true;Encrypt=false"
    ports:
      - "5000:80"
    depends_on:
      - sql-server
    
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    restart: always
    environment:
      - SA_PASSWORD=Ali1234567
      - ACCEPT_EULA=Y
    ports:
      - "14333:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
